###
GET http://localhost:9090/api/v1/orders
Content-Type: application/json
 
###
GET http://localhost:9090/api/v1/customers
Content-Type: application/json
###
GET http://localhost:9090/api/v1/cars
Content-Type: application/json

###
POST http://localhost:9090/api/v1/addcustomer
Content-Type: application/json

{
        "username": "Jakayla.Daniel",
        "name": "Ira O'Hara",
        "address": "272 Wolf Key",
        "email": "Amari17@yahoo.com",
        "phoneNumber": "442.430.4119 x391"
    }
  
###
POST http://localhost:9090/api/v1/addcar
Content-Type: application/json

  {
        "pricePerDay": 2287,
        "fabric": "Toshiba",
        "model": "C3767",
        "registrationNumber": "XCV089",
        "isBooked": false
    }

###
PUT http://localhost:9090/api/v1/updatecustomer
Content-Type: application/json

    {
        "id": 1,
        "username": "robin",
        "name": "Ellela1",
        "address": "centrum908776",
        "email": "elsisvenson@example.com",
        "phoneNumber": "098601"
     }
###
PUT http://localhost:9090/api/v1/updatecar
Content-Type: application/json

 {
        "id": 1,
        "pricePerDay": 660.0,
        "fabric": "Mazda08",
        "model": "Model20160",
        "registrationNumber": "REG08800",
        "isBooked": true
    }
###
DELETE http://localhost:9090/api/v1/deletecustomer
Content-Type: application/json

{"id":8
}
###
DELETE http://localhost:9090/api/v1/deletecar
Content-Type: application/json

{"id":6
}

###
DELETE http://localhost:9090/api/v1/deletecar
Content-Type: application/json

{"id":5
}